on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
    goreadme:
        permissions:
          contents: write
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v4
        - name: Fix for https://github.com/actions/runner/issues/2033 - dir from issue and docker run -v
          # Note how updating to newer checkout action did not resolve the issue, even if https://github.com/actions/checkout/issues/766 suggests it should have.
          run: mkdir -p /home/runner/work/_temp/_github_home && printf "[safe]\ndirectory = /github/workspace" > /home/runner/work/_temp/_github_home/.gitconfig
        - name: Fix for https://github.com/actions/runner/issues/2033 pt2 - dir from checkout v4 action
          run: mkdir -p /home/runner/work/_temp/_github_workflow && printf "[safe]\ndirectory = /github/workspace" > /home/runner/work/_temp/_github_workflow/.gitconfig
        - name: Update readme according to Go doc
          uses: posener/goreadme@v1
          with:
            badge-travisci: 'false'
            badge-codecov: 'false'
            badge-godoc: 'true'
            recursive: 'true'
            import-path: 'badc0de.net/pkg/factorioblueprint'
            functions: 'true'
            factories: 'true'
            methods: 'true'
            types: 'true'
            constants: 'true'
            email: 'goreadme@blackhole.bots.badc0de.net'
            # Optional: Token allows goreadme to comment the PR with diff preview.
            github-token: '${{ secrets.GITHUB_TOKEN }}'
